### ISSUE TITLE
Unknown action: SendMessage

### ISSUE THREAD

**Issue by vuk** [softwaremill/elasticmq#305]
Hello, 

I'm trying to get Elasticmq to work with  serverless-offline-sqs, but when i try doing 

```
sqs.sendMessage({
        MessageBody: 'body',
        QueueUrl: 'http://0.0.0.0:9324/demo-queue-dev',
        DelaySeconds: 0
    }, (err, data) => {
        console.log(err, data);
    })
```

I get an error saying `InvalidAction: InvalidAction; see the SQS docs`. 
When I look at elasticmq log i see `WARN  o.e.r.s.TheSQSRestServerBuilder$$anon$1 - Unknown action: SendMessage`

My settings in serverless.yml file are as follows: 

```
custom:
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:9324
    region: eu-west-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false

resources:
  Resources:
    DemoQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: demo-queue-${self:provider.stage}
```

I also tried with URL `http://0.0.0.0:9324/queue/demo-queue`, but in this case I get a different error, that queue doesn't exist, and server log says
