### ISSUE TITLE
latest MQ version is unable to create queues

### ISSUE THREAD

**Issue by vk9551** [softwaremill/elasticmq#410]
We are using docker image and it has no issues with release, 0.15.7
here are some logs 

```
localsqs_1       | 22:33:44.811 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.15.7) ...
localsqs_1       | 22:33:44.842 [elasticmq-akka.actor.default-dispatcher-6] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
localsqs_1       | 22:33:44.844 [elasticmq-akka.actor.default-dispatcher-10] INFO  c.t.sslconfig.akka.AkkaSSLConfig - ssl-config.default is true, using the JDK's default SSLContext
localsqs_1       | 22:33:44.845 [elasticmq-akka.actor.default-dispatcher-10] WARN  c.t.sslconfig.akka.AkkaSSLConfig - You are using ssl-config.default=true and have a weak certificate in your default trust store! (You can modify akka.ssl-config.disabledKeyAlgorithms to remove this message.) WARNING arguments left: 1
localsqs_1       | 22:33:44.848 [elasticmq-akka.actor.default-dispatcher-9] WARN  c.t.sslconfig.akka.AkkaSSLConfig - You are using ssl-config.default=true and have a weak certificate in your default trust store! (You can modify akka.ssl-config.disabledKeyAlgorithms to remove this message.) WARNING arguments left: 1
localsqs_1       | 22:33:44.848 [elasticmq-akka.actor.default-dispatcher-9] WARN  c.t.sslconfig.akka.AkkaSSLConfig - You are using ssl-config.default=true and have a weak certificate in your default trust store! (You can modify akka.ssl-config.disabledKeyAlgorithms to remove this message.) WARNING arguments left: 1
localsqs_1       | 22:33:44.848 [elasticmq-akka.actor.default-dispatcher-9] WARN  c.t.sslconfig.akka.AkkaSSLConfig - You are using ssl-config.default=true and have a weak certificate in your default trust store! (You can modify akka.ssl-config.disabledKeyAlgorithms to remove this message.) WARNING arguments left: 1
localsqs_1       | 22:33:44.848 [elasticmq-akka.actor.default-dispatcher-8] WARN  c.t.sslconfig.akka.AkkaSSLConfig - You are using ssl-config.default=true and have a weak certificate in your default trust store! (You can modify akka.ssl-config.disabledKeyAlgorithms to remove this message.) WARNING arguments left: 1
localsqs_1       | 22:33:44.851 [elasticmq-akka.actor.default-dispatcher-11] INFO  o.elasticmq.actor.QueueManagerActor - Creating queue QueueData(dlq_omniarchive,MillisVisibilityTimeout(30000),PT0S,PT0S,2020-10-28T22:33:44.851Z,2020-10-28T22:33:44.851Z,None,false,false,None,None,Map())
localsqs_1       | 22:33:44.851 [elasticmq-akka.actor.default-dispatcher-13] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Started SQS rest server, bind address 0.0.0.0:9324, visible server address * (depends on incoming request path) 
localsqs_1       | 22:33:44.851 [elasticmq-akka.actor.default-dispatcher-13] INFO  o.elasticmq.actor.QueueManagerActor - Creating queue QueueData(cds_omniarchive_queue,MillisVisibilityTimeout(30000),PT0S,PT0S,2020-10-28T22:33:44.851Z,2020-10-28T22:33:44.851Z,Some(DeadLettersQueueData(dlq_omniarchive,4)),false,false,None,None,Map())
localsqs_1       | 22:33:44.851 [main] INFO  org.elasticmq.server.Main$ - === ElasticMQ server (0.15.7) started in 42 ms ===
```

But latest docker image has elastic mq changes and we are seeing issues with this build. It didn't create the required queue that we mentioned in the conf file.

conf file: 
```
// this is mostly copy pasted from elasticMQ's README.md
// https://github.com/softwaremill/elasticmq

include classpath("application.conf")

// What is the outside visible address of this ElasticMQ node
// Used to create the queue URL (may be different from bind address!)
node-address {
    protocol = http
    host = "*"
    port = 9324
    context-path = ""
}

rest-sqs {
    enabled = true
    bind-port = 9324
    bind-hostname = "0.0.0.0"
    // Possible values: relaxed, strict
    sqs-limits = strict
}

// Should the node-address be generated from the bind port/hostname
// Set this to true e.g. when assigning port automatically by using port 0.
generate-node-address = false

queues {
  cds_omniarchive_queue {
     receiveMessageWait = 0 seconds
     deadLettersQueue {
         name = "dlq_omniarchive"
         maxReceiveCount = 4
     }
   }
   dlq_omniarchive { }
}

```

logs:
```
localsqs_1       | 18:07:46.392 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.15.8) ...
localsqs_1       | 18:07:46.451 [elasticmq-akka.actor.default-dispatcher-6] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
localsqs_1       | 18:07:46.463 [elasticmq-akka.actor.default-dispatcher-9] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Started SQS rest server, bind address 0.0.0.0:9324, visible server address http://localhost:9324
localsqs_1       | 18:07:46.463 [main] INFO  org.elasticmq.server.Main$ - === ElasticMQ server (0.15.8) started in 72 ms ===
```

**Comment by wojciechUrbanski** [comment]
Hi,

Thanks for the report. 

Could You provide command via which You are starting elasticmq and specify whether You are using native elasticmq or "normal" one?

**Comment by adamw** [comment]
Judging on 72ms startup I would suspect native :)

**Comment by wojciechUrbanski** [comment]
In newest version (0.15.8) we have unified way of running native elasticmq and the "normal one". 

In 0.15.7, to attach custom config to native elasticmq image was to mount it as `path/custom.conf:/opt/docker/elasticmq.conf`, in 0.15.8, the path has been changed to `path/custom.conf:/opt/elasticmq.conf`.

**Comment by iStefo** [comment]
We're experiencing similar problems.

This works fine (old version):

```yml
    sqs:
        image: softwaremill/elasticmq-native:0.15.7
        container_name: insights_elasticmq
        volumes:
            - ./_dev/sqs/elasticmq.conf:/opt/docker/elasticmq.conf:ro
        ports:
            - "9324:9324"
```

However, this doesn't:

```yml
    sqs:
        image: softwaremill/elasticmq-native:0.15.8
        container_name: insights_elasticmq
        volumes:
            - ./_dev/sqs/elasticmq.conf:/opt/elasticmq.conf:ro
        ports:
            - "9324:9324"
```

When using the second config, our elixir (ex_aws) client fails with this message:

```
[error] Unable to fetch events from AWS. Reason: {:http_error, 400, %{code: "AWS.SimpleQueueService.NonExistentQueue", detail: nil, message: "AWS.SimpleQueueService.NonExistentQueue; see the SQS docs.", request_id: "00000000-0000-0000-0000-000000000000", type: "Sender"}}
```

With 0.15.7, it works.

**Comment by l0phius** [comment]
I just tried this using 0.15.7 and i'm receiving the same error you posted above so i'm now thinking it may be a boto change?  Curious what version of boto are you using.  I'm actually using boto3 (latest version). just my two cents.

**Comment by vk9551** [comment]
> In newest version (0.15.8) we have unified way of running native elasticmq and the "normal one".
> 
> In 0.15.7, to attach custom config to native elasticmq image, You had to mount it as `path/custom.conf:/opt/docker/elasticmq.conf`, in 0.15.8, the path has been changed to `path/custom.conf:/opt/elasticmq.conf`.

I tried this option and it solved the issue.

**Comment by l0phius** [comment]
Yep! @vk9551 I changed my docker-compose when using 0.15.7 to this and it worked perfectly


```
version: '3.7'

services:
  elasticmq:
    image: softwaremill/elasticmq-native:0.15.7
    container_name: elasticmq
    ports:
      - "9324:9324"
    volumes:
      - ./elasticmq/custom.conf:/opt/docker/elasticmq.conf
```

Still there's an issue with 0.15.8 and not sure what that is though....

**Comment by vk9551** [comment]
```
version: '3.7'

services:
  elasticmq:
    image: softwaremill/elasticmq-native:0.15.8
    container_name: elasticmq
    ports:
      - "9324:9324"
    volumes:
      - ./elasticmq/custom.conf:/opt/elasticmq.conf
```

i tried this option and it worked for me.
