### ISSUE TITLE
Unable to creque queue on startup

### ISSUE THREAD

**Issue by joaocasarin** [softwaremill/elasticmq#716]
The title explains itself, but basically what I tried is:
This is my `elastic-mq/custom.conf`:
```conf
# the include should be done only once, at the beginning of the custom configuration file
include classpath("application.conf")

queues {
    express-k8s-local.fifo {
        defaultVisibilityTimeout = 10 seconds
        delay = 5 seconds
        receiveMessageWait = 0 seconds
        fifo = true
    }
}
```

This is my `docker-compose`:
```yml
version: '3.9'

services:
    elastic-mq:
        container_name: queue
        image: softwaremill/elasticmq-native:1.3.9
        restart: always
        ports:
            - 9324:9324
            - 9325:9325
        volumes:
            - ./elastic-mq/custom.conf:/opt/elasticmq.conf

```

The conf file is copied, but no queue is created as you can see here:
![image](https://user-images.githubusercontent.com/48847394/183804132-d9e6cf02-8c10-464d-ba7e-d93c6ff362a5.png)

Apparently no error was thrown:
![image](https://user-images.githubusercontent.com/48847394/183804297-02ae64e9-6b6a-46b1-a9c8-6d4c2a88ee51.png)

And I also tried this:
```yml
version: '3.9'

services:
    elastic-mq:
        container_name: queue
        build:
            context: ./containers
            dockerfile: Dockerfile
            target: queue
        restart: always
        ports:
            - 9324:9324
            - 9325:9325
```

And the `containers/Dockerfile` is:
```Dockerfile
FROM softwaremill/elasticmq-native:1.3.9 as queue
COPY ../elastic-mq/custom.conf /opt/elasticmq.conf
```

And the result is this error right in the container creation:
![image](https://user-images.githubusercontent.com/48847394/183804399-0e3f7219-7375-4f72-bdf0-49ab54b3a1f1.png)
