### ISSUE TITLE
Publishing messages with delay does not work as expected

### ISSUE THREAD

**Issue by Zakharen** [softwaremill/elasticmq#882]
I'm using elasticmq image. Here is a part of my docker compose config:

```
elasticmq:
    image: softwaremill/elasticmq
    container_name: aws_sqs_mock
    ports:
      - ${AWS_SQS_PORT}
      - ${AWS_SQS_UI_PORT}
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf
    networks:
      - paynet
```

here is elasticmq.conf with the following settings:

```
include classpath("application.conf")

node-address {
    host = aws_sqs_mock
}

queues {
    payslipPublished {
        defaultVisibilityTimeout = 30 seconds
        delay = 10 seconds
        receiveMessageWait = 0 seconds
    }
}
```

I was expecting to see a 10-second delay between each message I publish, but instead, I don't see any delay.
